#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/nems-event-processor
export NHS_SERVICE=nems-event-processor

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function configure_local_envs {
  export AWS_REGION=${AWS_DEFAULT_REGION}
  export LOCALSTACK_URL="http://localhost:4566"
}


##############
# Localstack #
##############

function die_localstack_die {
  echo docker processes running: $(docker ps)

  DOCKER_CONTAINERS_ON_PORT=$(docker ps --filter publish=4566 -q)

  echo docker processes running on expected localstack port: $DOCKER_CONTAINERS_ON_PORT

  if [ -z "$DOCKER_CONTAINERS_ON_PORT" ]; then
    echo no localstack nonsense going on, cool
  else
    echo trying to kill localstack...
    docker stop $DOCKER_CONTAINERS_ON_PORT
  fi
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  teardown_localstack)
      die_localstack_die
      ;;
  _build)
      rm -rf build/
      gradle assemble
      ;;
  _test_unit)
      gradle test
      ;;
  _test_integration)
      shift
      gradle --info integration $*
      ;;
  _test_coverage)
      gradle jacocoTestCoverageVerification
      ;;
  _code_quality)
      gradle check -x test -x integration
      ;;
  _test_all)
      configure_local_envs
      ./gradlew test integration jacocoTestCoverageVerification check
      ;;
  run_local)
      configure_local_envs
      ./gradlew bootRun
      ;;
  run_localstack_local)
      docker-compose -f docker-compose.localstack-local.yaml up -d
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
