#!/bin/bash

set -Eeo pipefail

aws_region=eu-west-2
image_repo_name=registrations/mesh-inbox-s3-forwarder

function validate_image_tag {
  if [ -z $IMAGE_TAG ]; then
    echo "Please set IMAGE_TAG environment variable"
    exit 1
  fi
}

function build_docker {
  validate_image_tag
  ./tasks generate-requirements
  FULL_LOCAL_IMAGE_TAG=${image_repo_name}:${IMAGE_TAG}
  docker build -t $FULL_LOCAL_IMAGE_TAG .
}

for command in "$@"
do
  echo "--- ${command} ---"
  case "${command}" in
    format)
        pipenv run format-import
        pipenv run format
        ;;
    check-format)
        pipenv run check-format
        ;;
    lint)
        pipenv run lint-flake8
        pipenv run lint-bandit
        ;;
    typecheck)
        pipenv run typecheck
        ;;
    check-deps)
        pipenv check \
          --ignore 51457 # CVE-2022-42969 in unused code see https://github.com/pytest-dev/pytest/issues/10392
        ;;
    validate)
        ./tasks check-format typecheck lint test
        ;;
    clean)
        find ./tests -type f -name "*.pyc" -delete
        find ./tests -type d -name "__pycache__" -delete
        find ./src -type f -name "*.pyc" -delete
        find ./src -type d -name "__pycache__" -delete
        find ./src -type f -path "*.egg-info*" -delete
        find ./src -type d -path "*.egg-info" -delete
        rm -rf build/ dist/ .pytest_cache/
        ;;
    devenv)
        echo "./tasks validate" > .git/hooks/pre-commit
        chmod +x .git/hooks/pre-commit
        pipenv install -d
        ;;
    test_unit)
        python -m pip install -U pipenv
        pipenv install -d
        pipenv run test
        ;;
    dep)
        ./tasks check-deps > audit-output.txt
        ;;
    _generate-requirements)
        pipenv lock -r > requirements.txt
        ;;
    generate-requirements)
        ./tasks _generate-requirements
        ;;
    build-docker)
        build_docker
        ;;
    publish-docker)
        build_docker

        aws_account_id=$(get_aws_account_id)
        repository_uri=${aws_account_id}.dkr.ecr.${aws_region}.amazonaws.com/${image_repo_name}

        docker tag $FULL_LOCAL_IMAGE_TAG ${repository_uri}:${IMAGE_TAG}
        docker tag $FULL_LOCAL_IMAGE_TAG ${repository_uri}:latest

        eval $(docker_login)
        docker push ${repository_uri}:${IMAGE_TAG}
    ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
  esac
done

set +e
